#!/usr/bin/env bash
#Script that displays numbers 1 to 100 and prints FizzBuzz when the number is
#a multiple of 3 and 5, prints Fizz on multiples of 3, and Buzz on multiples of
#5


i=1

while [ $i -le 100 ]
do
	if [ $((i % 15)) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	(( i++ ))
done
