#!/usr/bin/env bash
#Script uses while loop to print Best School 10 times, but on the 9th time uses an if then  statement to change the iteration to print HI


i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( i++ ))
done
