#!/usr/bin/env bash
#Script uses while loop to count numbers 1-20 but displays bad luck from China
#on the 4th iteration, bad luck from Japan on the 9th iteration, and bad luck 
#from Italy on the 17th iteration.

i=1
while [ $i -le 20 ]
do
	echo "$i"

	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
	esac


	(( i++ ))
done
