#!/usr/bin/env bash
#Script uses while loop to count numbers 1-20 but displays bad luck from China
#on the 4th iteration, bad luck from Japan on the 9th iteration, and bad luck 
#from Italy on the 17th iteration.

i=1
while [ $i -le 20 ]
do
	if [ $i = 4 ]
	then
		echo "bad luck from China"
	
	elif [ $i = 9 ]
	then
		echo "bad luck from Japan"
	
	elif [ $i = 17 ]
	then
		echo "bad luck from Italy"
	
	else
		echo "$i"
	fi
	
	(( i++ ))
done
