#!/usr/bin/env bash
#Script uses if and else statements that determines if the file exist,
#if it is empty, and if is a regular file or not. 


if [ -e ~/school ]
then
	echo "school file exists"
	if [ -s school ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"

fi

if [ -f ~/school ]
then
	echo "school is a regular file"
fi
